//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SembolMes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string kullaniciadi {
            get {
                return ((string)(this["kullaniciadi"]));
            }
            set {
                this["kullaniciadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sifre {
            get {
                return ((string)(this["sifre"]));
            }
            set {
                this["sifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.44")]
        public string server_sql {
            get {
                return ((string)(this["server_sql"]));
            }
            set {
                this["server_sql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SEMBOL_22")]
        public string database_sql {
            get {
                return ((string)(this["database_sql"]));
            }
            set {
                this["database_sql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hbs")]
        public string user_id_sql {
            get {
                return ((string)(this["user_id_sql"]));
            }
            set {
                this["user_id_sql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240305")]
        public string password_sql {
            get {
                return ((string)(this["password_sql"]));
            }
            set {
                this["password_sql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MES_21")]
        public string database_mes_sql {
            get {
                return ((string)(this["database_mes_sql"]));
            }
            set {
                this["database_mes_sql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.59")]
        public string mysql_server {
            get {
                return ((string)(this["mysql_server"]));
            }
            set {
                this["mysql_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dyilmaz@sembolotomotiv.com.tr")]
        public string oneri_gonderen_mail {
            get {
                return ((string)(this["oneri_gonderen_mail"]));
            }
            set {
                this["oneri_gonderen_mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itasgeyen@sembolotomotiv.com.tr")]
        public string oneri_alici_mail {
            get {
                return ((string)(this["oneri_alici_mail"]));
            }
            set {
                this["oneri_alici_mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dy155155")]
        public string oneri_gonderen_sifre {
            get {
                return ((string)(this["oneri_gonderen_sifre"]));
            }
            set {
                this["oneri_gonderen_sifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dyilmaz@sembolotomotiv.com.tr")]
        public string ariza_gonderen_mail {
            get {
                return ((string)(this["ariza_gonderen_mail"]));
            }
            set {
                this["ariza_gonderen_mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dy155155")]
        public string ariza_gonderen_sifre {
            get {
                return ((string)(this["ariza_gonderen_sifre"]));
            }
            set {
                this["ariza_gonderen_sifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yguneysu@sembolotomotiv.com.tr")]
        public string ariza_alici_mail {
            get {
                return ((string)(this["ariza_alici_mail"]));
            }
            set {
                this["ariza_alici_mail"] = value;
            }
        }
    }
}
